### ISSUE TITLE
Timer running not properly for 520 nm

### ISSUE THREAD

**Issue by pawelkulig1** [LemurPwned/spintronics-visual#101] opened 2018-05-11 15:43 UTC
There is problem for this data, with matplotlib it plots in weird manner. At the beginning it plots slowly but it starts to accelerate on time, middle part of plot is very fast and before end it's slower.

**Comment by LemurPwned** [comment] 2018-05-11 15:45
Ok i will take care of this. It is actually not a bug. The staging must agree with opengl plot therefore it "waits" for opengl to change and changes for matplotlib are not always equal because of the invalid number of entry datapoints in odt files

**Comment by LemurPwned** [comment] 2018-05-11 15:47
I will fix this later by adding an option to synchronize opengl to matplotlib. However, this time the situation will be reversed. Matplotlib plots will be waiting for opengl. Thus opengl drawing will vary in speed

**Comment by LemurPwned** [comment] 2018-05-15 11:00
This will be fixed along with #109

**Closed** 2018-06-18 11:33 UTC
Labels: Before Release, bug
